### ISSUE TITLE
Rename the repo

### ISSUE THREAD

**Issue by okonet** [netlify/eslint-config-netlify#1]
For the consistency with all other `eslint-config-*` repositories I'd suggest we rename this to `eslint-config-netlify`

Another option would be to make it more generic and put also stylelint config in it. In this case we'll have 2 `package.json` for eslint and stylelint. Not sure what option is better — 2 repositories or one with all coding standards.

Let's discuss

**Comment by calavera** [comment]
I've renamed the repo
