### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by okonet** [netlify/eslint-config-netlify#2]
We should publish `eslint-config-netlify` to npm so we can have SemVer versioning for it. In this case we projects can depend on it safely even if we introduce breaking changes. Right now, installing directly from GH will always pull latest `master` which will eventually break things.

**Comment by cassiozen** [comment]
Closed because, at least for now, we can tag specific releases on package.json:

```
"eslint-config-netlify": "github:netlify/eslint-config-netlify#1.4.0",
```
